### ISSUE TITLE
Buggify.exe / pyinstaller

### ISSUE THREAD

**Issue by roovyshapiro** [roovyshapiro/Buggify#14]
@sc1341 
Are you using a MAC? When using pyinstaller, it creates an executable that only works for the OS that it was run on. That would explain why it's not running for me. Perhaps we need to rename it?

**Comment by sc1341** [comment]
Ah yes sorry, I am on a mac. Personally I would be okay if we held off on the executable version of the program for now and put the instructions back into the README.md on how to create it (I can't remember if I added it back in the new version or not in the latest PR). That way we won't have to worry about having an outdated version every time we want to commit. Then when we get to a more finished product we can put in an executable for windows and mac... What are your thoughts on this?

**Comment by roovyshapiro** [comment]
I agree. We don't need this .exe yet so I added a commit to delete it. We can always recreate it later when we're ready to polish it for various OS'es. The instructions are already in the README showing the pyinstaller commands so I think this is fine for now.

@sc1341 Thank you!
